pom.xml
- Generate a jar with all dependencies
- Define the main class in the manifest
=> Improve maven integration

src/main/java/fr/inria/sacha/spoon/diffSpoon/CtDiff.java, src/main/java/fr/inria/sacha/spoon/diffSpoon/DiffSpoon.java, src/test/java/fr/inria/sacha/spoon/diffSpoon/CDiffTest.java, src/test/java/fr/inria/sacha/spoon/diffSpoon/DiffSpoonTest.java
- Use the spoon elements to print the actions code
- Add the location of each action
=> Improve the string representation of CtDiff

LICENSE.txt, README.md, pom.xml
=> chore(license): Adds apache license.

pom.xml, src/main/java/gumtree/spoon/diff/ActionClassifier.java, src/main/java/gumtree/spoon/diff/DiffImpl.java
Gumtree dependency isn't compatible with Java 7.
See here: https://github.com/GumTreeDiff/gumtree/blob/develop/build.gradle#L17-L18
=> feat(java): Upgrades to Java 8.

src/main/java/gumtree/spoon/builder/LabelFinder.java
The PR simplify the debug of gumtree output and fix an NPE when there is a CtSuperAccess in the analysed code
=> improves label and fix npe on CtSuperAccess

src/main/java/gumtree/spoon/builder/TreeScanner.java, src/test/java/gumtree/spoon/AstComparatorTest.java, src/test/resources/examples/chart18/DefaultKeyedValues2D.java, src/test/resources/examples/chart18/new_DefaultKeyedValues2D.java
This PR removes some elements from GumTree to improve the diff results.
* implicit element
* block
* reference
=> do not add some elements in GumTree

src/main/java/gumtree/spoon/AstComparator.java, src/test/java/gumtree/spoon/TreeTest.java
which involved a failure when calling getPath
=> [bugfix] the package of a CtClass created from a file was incorrect,

src/main/java/gumtree/spoon/builder/NodeCreator.java, src/test/java/gumtree/spoon/AstComparatorTest.java
=> add support for "throws"

src/main/java/gumtree/spoon/builder/LabelFinder.java
=> change "break" to "continue"  in visitCtContinue.

src/main/java/gumtree/spoon/builder/CtVirtualElement.java, src/main/java/gumtree/spoon/builder/CtWrapper.java, src/main/java/gumtree/spoon/builder/NodeCreator.java, src/test/java/gumtree/spoon/TreeTest.java, src/test/resources/examples/919148/ReplicationRun/919148_ReplicationRun_0_s.java, src/test/resources/examples/919148/ReplicationRun/919148_ReplicationRun_0_t.java, src/test/resources/examples/issue84_1/file_s.java, src/test/resources/examples/issue84_1/file_t.java, src/test/resources/examples/issue84_2/file_s.java, src/test/resources/examples/issue84_2/file_t.java
Creation of nodes for elements not included in the Spoon model
=> fix for issue #84

src/main/java/gumtree/spoon/builder/LabelFinder.java, src/main/java/gumtree/spoon/builder/NodeCreator.java, src/main/java/gumtree/spoon/builder/TreeScanner.java, src/test/java/gumtree/spoon/AstComparatorTest.java, src/test/resources/examples/spoon.json
#96 
This PR allows us to consider extends arguments//superclass and introduces the corresponding test cases.
=> Fix #96: consider superclass

src/main/java/gumtree/spoon/builder/LabelFinder.java, src/test/java/gumtree/spoon/AstComparatorTest.java, src/test/java/gumtree/spoon/TreeTest.java, src/test/resources/examples/d4j/Lang_57/LocaleUtils/Lang_57_LocaleUtils_s.java, src/test/resources/examples/d4j/Lang_57/LocaleUtils/Lang_57_LocaleUtils_t.java, src/test/resources/examples/d4j/Math_34/ListPopulation/Math_34_ListPopulation_s.java, src/test/resources/examples/d4j/Math_34/ListPopulation/Math_34_ListPopulation_t.java, src/test/resources/examples/spoon.json
name instead of the signature.
=> [bugfix] issue #102. A tree node of an invocation  has now the simple

src/main/java/gumtree/spoon/AstComparator.java, src/test/java/gumtree/spoon/AstComparatorTest.java
=> add arguments to pass the paths corresponding to the files under

pom.xml, src/test/java/gumtree/spoon/AstComparatorTest.java, src/test/java/gumtree/spoon/diff/DiffTest.java, src/test/resources/examples/spoon.json
Some diffs are better some are worse. It's overall slightly better.
=> bump to Spoon 7.6

src/main/java/gumtree/spoon/AstComparator.java, src/main/java/gumtree/spoon/builder/LabelFinder.java, src/main/java/gumtree/spoon/builder/TreeScanner.java, src/test/java/gumtree/spoon/AstComparatorTest.java, src/test/java/gumtree/spoon/TreeTest.java, src/test/resources/examples/diffcomment1/1205753_EmbedPooledConnection_0_s.java, src/test/resources/examples/diffcomment1/1205753_EmbedPooledConnection_0_t.java, src/test/resources/examples/diffcomment2/1205753_EmbedPooledConnection_0_s.java, src/test/resources/examples/diffcomment2/1205753_EmbedPooledConnection_0_t.java, src/test/resources/examples/diffcomment3/RectangularCholeskyDecomposition_s.java, src/test/resources/examples/diffcomment3/RectangularCholeskyDecomposition_t.java, src/test/resources/examples/spoon.json
comments have as label the comment itself (before it put an empty
string).
=> option for include/exclude the Comments in the metadata. If included,

src/main/java/gumtree/spoon/AstComparator.java, src/test/java/gumtree/spoon/AstComparatorTest.java
Fix #120
See [GumTree parameters for the properties used here](https://github.com/GumTreeDiff/gumtree/wiki/Parameters)
=> Correctly set GumTree system properties

src/main/java/gumtree/spoon/diff/ActionClassifier.java, src/test/java/gumtree/spoon/AstComparatorTest.java
Functionality created from @khaes-kth
=> method for replacing moves by Insert/Deletes

pom.xml
in order to fix continuous delivery failure
=> update javadoc plugin

pom.xml
Reference: #176 
I shall update junit version in some other PR because that would require changes in import statements and some APIs which may be a lot.
=> chore: update spoon version to `9.1.0`

src/main/java/gumtree/spoon/builder/LabelFinder.java, src/main/java/gumtree/spoon/builder/NodeCreator.java, src/main/java/gumtree/spoon/builder/TreeScanner.java, src/test/java/gumtree/spoon/AstComparatorTest.java, src/test/java/gumtree/spoon/TreeTest.java, src/test/resources/examples/spoon.json
=> fix: make super type node a direct descendant of class node

src/main/java/gumtree/spoon/builder/NodeCreator.java, src/test/java/gumtree/spoon/diff/DiffTest.java, src/test/resources/examples/superInterfaces/insertion/left.java, src/test/resources/examples/superInterfaces/insertion/right.java
=> fix: ensure insertion of node metadata is incorporated in the edit script

src/main/java/gumtree/spoon/AstComparator.java, src/main/java/gumtree/spoon/diff/DiffConfiguration.java, src/main/java/gumtree/spoon/diff/DiffImpl.java, src/test/java/gumtree/spoon/AstComparatorTest.java, src/test/java/gumtree/spoon/TreeTest.java, src/test/java/gumtree/spoon/diff/DiffTest.java
=> Issue #287: Changing default gumtree matcher

src/main/java/gumtree/spoon/builder/LabelFinder.java
fix https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/295
=> Issue #295: Fix NPE When visit annotation type

renovate.json
If checks are green, we should auto-merge :)
=> chore: automerge PRs by renovate

src/main/java/gumtree/spoon/builder/LabelFinder.java, src/main/java/gumtree/spoon/diff/DiffImpl.java, src/test/java/gumtree/spoon/AstComparatorTest.java, src/test/resources/examples/issue347b/DifferentInsertionFirst.java, src/test/resources/examples/issue347b/DifferentInsertionSecond.java
fix #347
supersedes https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/355
=> fix #2 of https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/347
