- src/main/java/gumtree/spoon/AstComparator.java
Empty java files used to throw an error when getting all factory Types.
It is now fixed.
> Fix: Empty java files

- src/main/java/gumtree/spoon/diff/DiffImpl.java
- src/test/java/gumtree/spoon/AstComparatorTest.java
The root has all info. The reason is the metadata is written after
converting to spoon all ops, and before the convertion of root.
> [bugfix, critical] the Operations from AllOps have NULL the dst node.

- src/main/java/gumtree/spoon/builder/NodeCreator.java
- src/main/java/gumtree/spoon/diff/Diff.java
- src/main/java/gumtree/spoon/diff/DiffImpl.java
- src/main/java/gumtree/spoon/diff/operations/Operation.java
- src/test/java/gumtree/spoon/AstComparatorTest.java
- src/test/resources/examples/testDuplicateOperations/left.java
- src/test/resources/examples/testDuplicateOperations/right.java
add a failing test case for duplicate operations return by Diff.getAllOperations()
> fix: fix confusing debug toString for modifier Itree nodes which have no corresponding real Spoon node

- src/main/java/gumtree/spoon/builder/CtVirtualElement.java
- src/main/java/gumtree/spoon/builder/NodeCreator.java
- src/test/java/gumtree/spoon/AstComparatorTest.java
- src/test/resources/examples/spoon.json
We add to the label of nodes "Modifiers" the class of the modifiable class. So, for instance, the modifiers of a class can be only matched with those from another class, (preventing matching
with modifiables of parameters, methods, etc).
Detailed explanation:
I found the bug and a possible solution.
Bug: before we had GumTree nodes Modifiers that grouped the modifiers of a CtModifiable (Method, class, param, field, etc). The last change I introduced added a Virtual Node for those modifiers that are not included in the spoon model, but that's not related to the bug (I think).
The problem is when matching modifiers: GT finds several of Trees with similar shape (i.e., Modifier root with child public), so in the buggy code it matches the modifiers of one CtElement (e.g., method) with those …
> [bugfix] fixing #86. Matching 'compatible' modifiers

- src/main/java/gumtree/spoon/builder/NodeCreator.java
- src/test/java/gumtree/spoon/AstComparatorTest.java
- src/test/resources/examples/spoon.json
Avoid creating Modifiers node when the Modifiable element has not any modifiers.
Related to issue #92 https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/92
> Avoid creating Modifiers node with any Modifiable element

- src/main/java/gumtree/spoon/builder/CtWrapper.java
This solves the NullPointerException mentioned in [this issue](https://github.com/SpoonLabs/coming/issues/177).
The problem with the old version is that the `factory` is not set for `CtWrapper` & `CtVirtualElement` instances. In this pull request, we set the same factory for such elements as the factory of their parents.
> factory is set for CtWrapper and CtVirtualElement

- pom.xml
Fixes #135 
Maven was not able to find the dependency version `8.2.0-SNAPSHOT` of spoon-core. These changes correct the version according to the instructions [here](http://spoon.gforge.inria.fr/#download).
> bump spoon core version

- pom.xml
Fixes #137 
Reference: https://stackoverflow.com/questions/52953483/logmanager-getlogger-is-unable-to-determine-class-name-on-java-11
`log4j` is a multi-release jar so running the project on Java 11 without `Multi-Release: true` wasn't working. Passing this flag instructed the runtime to get `log4j` compatible for version 11 which successfully executed the project.
> Fix fetching of log4j jar

- src/main/java/gumtree/spoon/builder/NodeCreator.java
- src/test/java/gumtree/spoon/diff/support/SpoonSupportTest.java
- src/test/resources/examples/roleInParent/final/left.java
- src/test/resources/examples/roleInParent/final/right.java
- src/test/resources/examples/roleInParent/modifiers/left.java
- src/test/resources/examples/roleInParent/modifiers/right.java
Fixes #160 
These changes explicitly assign `roleInParent` to the following elements.
- ~[ ] Super type~
I am not sure how I can test for the role of a `CtTypeReference` (`SUPER_TYPE` in this case). Need some help there.
> Fix role of `CtWrapper` elements in their parent

- src/main/java/gumtree/spoon/builder/CtVirtualElement.java
- src/test/java/gumtree/spoon/diff/support/SpoonSupportTest.java
Fixes #162 
- Did not write a test case as the API is not _computing_ anything. It just returns the `children`. We could test for visibility but I think that is out of scope.
- I hope the API name `getChildren()` is not confused with `getDirectChildren()` in spoon. If that is the case, I am open to suggestion for a better name.
> Add API to retrieve children of `CtVirtualElement`

- src/main/java/gumtree/spoon/builder/NodeCreator.java
- src/test/java/gumtree/spoon/diff/support/SpoonSupportTest.java
Fixes #166 
The PR refactors the node creation of `CtTypeReference`s. Initially, they were wrapped in `CtWrapper` and then stored as metadata. These changes **will not** wrap `CtTypeReference`s and directly store them corresponding to `spoon_object` key.
> Remove wrapper from instances of `CtTypeReference`

- src/main/java/gumtree/spoon/builder/NodeCreator.java
- src/test/java/gumtree/spoon/AstComparatorTest.java
- src/test/java/gumtree/spoon/diff/DiffTest.java
- src/test/resources/examples/diffOfGenericTypeReferences/builtInTypeToBuiltInType/left.java
- src/test/resources/examples/diffOfGenericTypeReferences/builtInTypeToBuiltInType/right.java
- src/test/resources/examples/diffOfGenericTypeReferences/builtInTypeToTypeParameter/left.java
- src/test/resources/examples/diffOfGenericTypeReferences/builtInTypeToTypeParameter/right.java
- src/test/resources/examples/diffOfGenericTypeReferences/typeParameterToBuiltInType/left.java
- src/test/resources/examples/diffOfGenericTypeReferences/typeParameterToBuiltInType/right.java
Fixes #157 
These changes would now allow the parser to detect generic types arguments. For example, `List<Integer>` -> `List<String>` or `SomeClass<A>` -> `SomeClass<B>`. In fact, this change discovered a bug in three of the existing test cases!
1. [test_issue201812](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/test/java/gumtree/spoon/AstComparatorTest.java#L1533)
2. [testModIfEmpty](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/test/java/gumtree/spoon/AstComparatorTest.java#L1724)
3. [test_action_RootOrder](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/test/java/gumtree/spoon/diff/DiffTest.java#L161)
**Missing operations** in each of them
1. [Delete TypeReference …
> fix: add generic type paramaters of variables in ITree

- src/main/java/gumtree/spoon/builder/LabelFinder.java
- src/test/java/gumtree/spoon/TreeTest.java
- src/test/java/gumtree/spoon/diff/DiffTest.java
- src/test/resources/examples/annotations/left.java
- src/test/resources/examples/annotations/right.java
Fixes #174 
The changes add a visitor for `CtAnnotation` which gets the corresponding label.
> fix: add labels in nodes for annotation

- src/main/java/gumtree/spoon/diff/operations/Operation.java
Initially, `Operation.toString()` would throw a `NullPointerException` because it tried to get the qualified name of the class its node belongs to. But it is not necessary that a Java file always has a class, and it may also have an interface. Thus, it's better to get `CtType`'s qualified name so that interface and classed both are accounted for.
> fix: retrieval of string representation of operation

- src/main/java/gumtree/spoon/builder/NodeCreator.java
- src/test/java/gumtree/spoon/TreeTest.java
- src/test/resources/examples/NestedReturnType.java
Reference: #183 
`RETURN_TYPE` couldn't be added to `TreeScanner` give its dependency on `computeTreeOfTypeReferences` which is in `NodeCreator`.
> fix: add support for parsing nested types in `RETURN_TYPE`

- src/main/java/gumtree/spoon/builder/NodeCreator.java
- src/test/java/gumtree/spoon/AstComparatorTest.java
- src/test/java/gumtree/spoon/diff/DiffTest.java
- src/test/resources/examples/thrownTypes/left.java
- src/test/resources/examples/thrownTypes/right.java
The changes group exceptions after the `throws` keyword into one root node - `THROWN_TYPES`. This is inspired by the approach followed in https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/181. Further, this root node has been wrapped in `CtVirtualElement` so that the problem analogous to https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/192 can also be dealt with.
https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/183: This node cannot be parsed using `TreeScanner` only because it deals with creating root nodes (wrapping child nodes in `CtVirtualElement`) which can only be done using `NodeCreator`.
> feat: introduce a collector node for thrown exceptions

- .github/workflows/publish.yml
The deployment script was not executing in https://github.com/SpoonLabs/gumtree-spoon-ast-diff/commit/b111c7d80c3a314f6173addf6bd98e6a4fb76b17 because I didn't use the [checkout action](https://github.com/actions/checkout). Thus, the workflow wasn't able to locate the `deploy_to_maven.sh` script.
> chore: fix deployment script with Actions

- README.md
The current badges were outdated since we don't use Travis now.
> docs: update badges for build status and deployment status

- .github/workflows/ci.yml
The changes enable the execution of workflows on PRs from forks. See https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/202#issuecomment-936886526.
> Pull requests from forks absolutely do trigger workflows if the pull_request target is specified in the workflow file. Just look at Spoon!
> chore: configure execution of workflows on PRs from forks

- src/main/java/gumtree/spoon/builder/NodeCreator.java
- src/test/java/gumtree/spoon/diff/DiffTest.java
Currently, if there is a diff such as,
```diff
class Test {
-     List<String> x;
+     List<? super Integer> x;
}
```
it is reported as an update operation even though their classes are different. `CtTypeReference` and `CtWildcardReference`, respectively, in this case. Although we [thought this was desirable](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/179#discussion_r708295302), it is proving to be a hindrance for ostracizing `UpdateOperation` from root operations.
As discussed [here](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/125#issuecomment-864620236), it would not be possible to provide a single role for this case as the spoon nodes are instances of different spoon classes. Moreover, even if we change values corresponding to `CtRole.NAME`, the …
> feat: split operation into insert and delete if their classes are different

- src/main/java/gumtree/spoon/builder/LabelFinder.java
It is not required to check if `Invocation.getExecutable` returns `null` because it never does. See the following two implementations of `getExecutable()`. Notice that it always assigns a default reference. 
1. https://github.com/INRIA/spoon/blob/8af9cceb0053ce109ebd0142f82daec5f928b970/src/main/java/spoon/support/reflect/code/CtConstructorCallImpl.java#L52-L60
2. https://github.com/INRIA/spoon/blob/8af9cceb0053ce109ebd0142f82daec5f928b970/src/main/java/spoon/support/reflect/code/CtInvocationImpl.java#L86-L94
> refactor: remove null check for executable while visiting invocation

- src/main/java/gumtree/spoon/builder/LabelFinder.java
- src/main/java/gumtree/spoon/builder/NodeCreator.java
- src/main/java/gumtree/spoon/builder/TreeScanner.java
- src/test/java/gumtree/spoon/TreeTest.java
- src/test/java/gumtree/spoon/diff/DiffTest.java
- src/test/resources/examples/annotationValues/firstInsert/left.java
- src/test/resources/examples/annotationValues/firstInsert/right.java
- src/test/resources/examples/annotationValues/insert/left.java
- src/test/resources/examples/annotationValues/insert/right.java
- src/test/resources/examples/annotationValues/updateMethod/left.java
- src/test/resources/examples/annotationValues/updateMethod/right.java
Fixes: #220 
The changes wrap values of `CtAnnotation` in `CtVirtualElement` which in turn wraps all the key-value pairs in `CtWrapper`. Note that this case is similar to how we deal with modifiers because values of annotation are not spoon nodes. They are of the form `Map.Entry<String, CtExpression>`.
However, there is one pending task before we move on to merging. ~The `rootOperations` also an update operation like in the linked issue along with two insert operations. The latter should not be reported because node in update operation is parent of the `srcNode`s in the insert operation. In my experience, the `ActionClassifier` should ignore the operation if a parent _at any level exists_. More technically, [this line](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/mai …
> feat: produce fine-grained AST diff for annotations

- src/main/java/gumtree/spoon/builder/LabelFinder.java
- src/test/java/gumtree/spoon/AstComparatorTest.java
- src/test/resources/examples/spoon.json
Fix #247 
Initially a diff between `super` and `this` was disregarded because both of those invocations were assigned the label `<init>`. The changes proposed in this PR assign `super` and `this` labels to the respective nodes.
> fix: differentiate `super` from `this` invocation

- pom.xml
- src/test/resources/examples/annotationValues/insert/left.java
- src/test/resources/examples/annotationValues/insert/right.java
Fixes #253 
The build was failing because the Jenkins build pulled the latest SNAPSHOT version of Spoon and it had the patch in [this commit](https://github.com/INRIA/spoon/commit/1ec339d04d9521593df7dea2dce1d263a74d2b9f). This caused a test failure in our project because the incorrect `CtType`s were being compared for AST difference.
I have fixed the failure by modifying the test so that the correct `CtType` is picked up. However, we should configure in Jenkins that it should use the version provided in POM. As of now, it uses [`inject_spoon_snapshot.py`](https://spoon.gforge.inria.fr/jenkins/inject_spoon_snapshot.py) to specify the version of Spoon the build is supposed to use. Is that intended, @monperrus ? I am assuming it is there so that gumtree-spoon maintainers become aware of …
> chore: update spoon to 10.2.0-beta-15

- src/main/java/gumtree/spoon/AstComparator.java
- src/main/java/gumtree/spoon/diff/DiffConfiguration.java
- src/main/java/gumtree/spoon/diff/DiffImpl.java
- src/test/java/gumtree/spoon/diff/DiffTest.java
- src/test/resources/examples/patch1-Math-20-Elixir-plausible/left.java
- src/test/resources/examples/patch1-Math-20-Elixir-plausible/right.java
Reference: https://github.com/GumTreeDiff/gumtree/issues/285
The patch in the linked issue was not _fine-grained_ enough so I had a discussion with @jrfaller and he told me about `HybridMatcher` that should work for us, and it does! Thankfully, replacing the matcher does not fail any of our tests (except one) so it seems like a good idea to do so.
> feat: add API to configure `Matcher`

- src/main/java/gumtree/spoon/builder/NodeCreator.java
- src/test/java/gumtree/spoon/TreeTest.java
- src/test/resources/examples/position/VirtualElementLeft.java
- src/test/resources/examples/position/VirtualElementRight.java
- src/test/resources/examples/position/WrapperLeft.java
- src/test/resources/examples/position/WrapperRight.java
**Missing Position Information Fix**
CtVirtualElement and CtWrapper objects do not contain the related position information. As this information is still useful, especially for debugging purposes, this fix correctly maps the objects to their position information during creation. For the case where CtWrapper objects represent more than one code element, the positions are merged.
Relates to: https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/199 and https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/132
Changes since previous pull request:
- Separated out invocation ordering fix 
- Removed `var` usage
- Extended testing
Remaining issues:
- Which contributors to include in the newly added (required) copyright/license headers
> Fix for missing position information

- .buildscript/deploy_to_maven.sh
1. Make `cURL` follow redirects. `search.maven.org` is redirected to `central.sonatype.com`.
2. Fix `jq` input.
> ci: fix release script

- src/main/java/gumtree/spoon/AstComparator.java
In cases where there are some syntax errors, gumtree-spoon-ast-diff outputs "no AST change"
This PR fixes that.
Right now, only the most serious cases are fixed.
If there are subtle syntax errors like missing a ";" or ")" and the rest matches, it will still output "no AST change" :/
> fix some "no AST change" when there are syntax errors

- src/main/java/gumtree/spoon/builder/NodeCreator.java
- src/main/java/gumtree/spoon/builder/SpoonGumTreeBuilder.java
- src/main/java/gumtree/spoon/builder/TreeScanner.java
- src/test/java/gumtree/spoon/SourcePositionTest.java
- src/test/java/gumtree/spoon/TreeTest.java
- src/test/resources/source-positions/Annotations.java
- src/test/resources/source-positions/Field.java
- src/test/resources/source-positions/Return.java
- src/test/resources/source-positions/SuperInterface.java
- src/test/resources/source-positions/ThrownType.java
- src/test/resources/source-positions/TypeAccess.java
- src/test/resources/source-positions/TypeArgument.java
- src/test/resources/source-positions/TypeCast.java
- src/test/resources/source-positions/VariableType.java
Fixes #323 
We record start and end position characters in each node in the Gumtree tree. Thankfully, Spoon nodes provide this information in these [two APIs](https://github.com/INRIA/spoon/blob/c60af45512223894e32a5fd2963079a88d22c388/src/main/java/spoon/reflect/cu/SourcePosition.java#L74-L82).
Most of the nodes in Spoon are visited in `TreeScanner` and they are added to Gumtree AST. However, there are many more nodes created in `NodeCreator` for which I have added the position manually. Hence, they require testing. This is why I am marking this PR as draft right now. I will add some tests soon and then merge. @pouryafard75, please try out this PR and report any bugs in the positions you get. It will also help me write tests. :)
> feat: record positions of each node in Tree

- src/test/java/gumtree/spoon/AstComparatorTest.java
- src/test/resources/examples/issue347/DifferentInsertionFirst.java
- src/test/resources/examples/issue347/DifferentInsertionSecond.java
- src/test/resources/examples/issue347/SameInsertionFirst.java
- src/test/resources/examples/issue347/SameInsertionSecond.java
See https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/347
This adds a couple of test cases to show that setting the `nolabel` property to true before calling the `Diff` ignores the labels and gives the expected output for the cases similar to the example test case(s) presented in the issue. 
There is a need to manually set and unset the `nolabel` system property before and after (respectively) each of the 2 test cases have computed their diff because quite a lot (around 70) test cases *fail* if the `nolabel` property is set to `true`. 
I am hopeful that these tests are not run "in parallel" -- ie, the property is set to `true`, and at the same time, another test is also executing (before the property could be "unset" again), which fails because of this property being `true`. 
If …
> test: Adding a couple of test cases for anonymous class

- src/main/java/gumtree/spoon/builder/LabelFinder.java
- src/test/java/gumtree/spoon/AstComparatorTest.java
See https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/347
This should use an empty string as the label for an anonymous class. Initially I tried using the checksum of the pretty-printed anonymous class contents like so (these additions were in `LabelFinder.java`): 
```java
// ... other content
private String getChecksum(String input) {
Checksum crc32 = new CRC32();
byte[] bytes = input.getBytes();
crc32.update(bytes, 0, bytes.length);
return Long.toHexString(crc32.getValue());
}
@Override
public void scanCtNamedElement(CtNamedElement e) {
if (e instanceof CtClass && ((CtClass<?>) e).isAnonymous()) {			
label = getChecksum(e.prettyprint());
} else {
label = e.getSimpleName();
}
}
// ... other content
```
Even though it seems to resolve the issue in …
> fix: using empty string as label for an anonymous CtClass
